"$schema" = "https://schema.tauri.app/config/2"
productName = "eracraft"
version = "0.1.0"
identifier = "com.era.eracraft"

[build]
beforeDevCommand = "cd ../frontend && pnpm dev"
devUrl = "http://localhost:3000"
beforeBuildCommand = "cd ../frontend && pnpm generate"
frontendDist = "../frontend/dist"

[app]

[[app.windows]]
title = "eracraft"
width = 800
height = 600

[app.security]
csp = ""

[bundle]
active = false
targets = "all"
icon = [
  "icons/32x32.png",
  "icons/128x128.png",
  "icons/128x128@2x.png",
  "icons/icon.icns",
  "icons/icon.ico"
]
